### ISSUE TITLE
How to install the theme in my project

### ISSUE THREAD

**Issue by MoaazGaballah** [crate/crate-docs-theme#141]
Hello, 
I have a nodejs project which i want to make it's documentation using crate-docs-theme.
How to install that theme ?
I tried to use pip install crate-docs-theme command that's referred in README file here https://github.com/crate/crate-docs-theme
but nothing installed ! i also searched for a installation guide on this link 
https://sphinx-themes.org/html/crate-docs-theme/crate/index.html
 but also nothing 

any kind of help will be appreciated

**Comment by joemoe** [comment]
hi @MoaazGaballah, to be honest the crate docs theme is heavily tide to our website and probably not that easy to get it running for any other none-cratedb project. 
maybe you can have a look at the setup of our guide: 
https://github.com/crate/guide
especially:
- https://github.com/crate/guide/blob/master/requirements.txt
- https://github.com/crate/guide/blob/master/bootstrap.sh
- https://github.com/crate/guide/blob/master/DEVELOP.rst
- https://github.com/crate/guide/blob/master/docs/conf.py

thanks, joe

**Comment by joemoe** [comment]
please also consider my latest pr: https://github.com/crate/crate-docs-theme/pull/143
