### ISSUE TITLE
Creating issues in the feedback box doesn't generate the correct page link

### ISSUE THREAD

**Issue by msbt** [crate/crate-docs-theme#189]
Example: https://crate.io/docs/crate/admin-ui/en/latest/index.html

If you scroll down and click on new issue, it should create
`Page URL: https://crate.io/docs/crate/admin-ui/en/latest/index.html` 
in the ticket body, but the "i" gets lost along the way and ends up like this:
`Page URL: https://crate.io/docs/crate/admin-u/en/latest/index.html`

**Comment by mechanomi** [comment]
thanks, @msbt!

the bug is here: https://github.com/crate/crate-docs-theme/blob/master/src/crate/theme/rtd/conf/crate_admin_ui.py#L27
