### ISSUE TITLE
add "team: tech writing" label to new feedback issues

### ISSUE THREAD

**Issue by mechanomi** [crate/crate-docs-theme#204]
at the moment, the feedback section adds "area: docs" but this is not sufficient for it to automatically pop up on the tech writing project board "add cards" default search

the theme should be modified so that creating a new feedback issue adds the "team: tech writing" label

**Comment by mechanomi** [comment]
fix here: https://github.com/crate/crate-docs-theme/pull/211

**Comment by infoverload** [comment]
Done: https://github.com/crate/crate-docs-theme/pull/211
