### ISSUE TITLE
the CrateDB Reference index shows unrelated feedback issues

### ISSUE THREAD

**Issue by mechanomi** [crate/crate-docs-theme#205]
see https://crate.io/docs/crate/reference/en/latest/

the feedback section shows this issue: https://github.com/crate/crate/issues/10119

this is wrong. looks like the GitHub issues search is not behaving as expected

**Comment by mechanomi** [comment]
fix here: https://github.com/crate/crate-docs-theme/issues/205

**Comment by infoverload** [comment]
Done
