### ISSUE TITLE
Canonical URL and sitemap URLs need to match

### ISSUE THREAD

**Issue by norosa** [crate/crate-docs-theme#220]
canonical url
https://crate.io/docs/sql-99/en/latest/appendices/
vs.
sitemap url
https://crate.io/docs/sql-99/en/latest/appendices/index.html

it seems that index.html gets stripped from the canonical url, same happens on this page here: https://crate.io/docs/sql-99/en/latest/chapters/index.html

not sure if this is by design, either way, if this is an issue, the tech writers need to adjust their buildtools to account for that

(from @msbt)

**Comment by amotl** [comment]
AFAIK, this is by design. The examples on [1] reflect the very same behavior. Please reopen this issue if this is actually a problem for anything or anyone.

[1] https://pypi.org/project/sphinx-sitemap/
