### ISSUE TITLE
Idea - Improve readability of documentation by highlighting admonitions with a background color

### ISSUE THREAD

**Issue by proddata** [crate/crate-docs-theme#221]
I think the readability of crate.io docs could be largely improved by highlighting admonitions with a background color like in the following picture.

---

![image](https://user-images.githubusercontent.com/23557193/94168580-13d8ae00-fe8e-11ea-9272-a115aaa6b229.png)

---

Admonitions symbols might need some adjustments

https://github.com/crate/crate-docs-theme/blob/master/src/crate/theme/rtd/crate/static/css/crateio-rtd.css

**Comment by scjimenez** [comment]
Many thanks, @proddata. @mechanomi: Would like to get your opinion on it. 🙂 @belringer created a draft, please find it enclosed. @msbt would take care of implementing it. As well, can you please tell me: Are all admonitions covered? 

![draft-docs-admonitions](https://user-images.githubusercontent.com/33090557/94542364-ff5b3380-0248-11eb-9bad-e723c33e224b.png)

**Comment by proddata** [comment]
❤️ it

I think there is a `danger` admonition.
Don't know if we have used it so far (there was no logo, but css styling)

**Comment by proddata** [comment]
Just realised, that also the menu/search is different 🥇

**Comment by msbt** [comment]
@proddata that's not part of this update, focus on the right part 😉

**Comment by mechanomi** [comment]
the SEEALSO icon should probably be a signpost icon or something. the arrows don't communicate "see also" to me

it would be cool to style up WARNING and DANGER with the skull icon

HOWEVER... if we're updating the admonition stylings...

... an idea that came up recently was to use these page elements as an excuse for using a goat as a mascot. I really like that idea. do you think it would be possible?

so in place of these rather abstract and generic icons (no offence! they do what they're meant to do well) -- we would replace each one with some illustration of a goat doing or expressing something that communicates the same idea

I really really love the idea of getting little goat mascot icons on the site. it could really make the whole site (docs included) feel a lot more friendly and a lot more "Crate" specific as opposed to generic

if we need help with the illustrations, we could reach out to Lily (ask Joe for contact details)

**Comment by proddata** [comment]
Like the goat idea, agree with the signpost.
Though for "readability" reasons, I think even dropping the logos all together would be an option. Putting even more complex ones there imho is a bit counter-productive. 

don't want to be a total killjoy though.

**Comment by scjimenez** [comment]
Many thanks, @mechanomi. Our design god @belringer says you can and will have 🐐s. We aka @msbt now implement what we have, 🐐s will follow as version 2. 🙂 @proddata You are no killjoy at all! But I only read you like the 🐐-idea. 😇
