### ISSUE TITLE
Multiple Google Analytics tags on the docs

### ISSUE THREAD

**Issue by scjimenez** [crate/crate-docs-theme#225]
Please find more information in the comments here: 
https://trello.com/c/MI4RQwZI/787-multiple-google-analytics-tags-on-the-docs

**Reference:**
https://docs.readthedocs.io/en/latest/advertising/advertising-details.html#analytics

**How to disable:**
https://docs.readthedocs.io/en/latest/guides/google-analytics.html#disabling-google-analytics-on-your-project

**Comment by msbt** [comment]
fixed together with https://github.com/crate/crate-docs-theme/pull/238 by @norosa (rtd setting)
