### ISSUE TITLE
Add meta description, OpenGraph and/or Twitter cards for better visibility in search engines

### ISSUE THREAD

**Issue by msbt** [crate/crate-docs-theme#236]
As suggested [here](https://github.com/crate/tech-writing-domain/issues/378), the SEO of our docs could do with a little improvement. Apparently the og stuff doesn't work out of the box, that's why the build process needs an update:

For OpenGraph, there's a [Sphinx extension](https://pypi.org/project/sphinxext-opengraph/).

The meta description could/should be added like this via RST: https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#use-meta-tags

On the main website we use this as our default image for og/meta/twitter cards: https://crate.io/wp-content/uploads/2020/10/crateio-logo.png

**Comment by amotl** [comment]
Can we also upload/use a logo variant with dimensions 320x168x72 somehow?

![image](https://user-images.githubusercontent.com/453543/119536319-3c9ca480-bd89-11eb-908d-3da78e55f17b.png)

**Comment by amotl** [comment]
Hi Matthias,

#269 adds and activates the Sphinx extension [sphinxext-opengraph](https://github.com/wpilibsuite/sphinxext-opengraph) to generate OpenGraph metadata (https://ogp.me/).

With kind regards,
Andreas.
