### ISSUE TITLE
CSS minification should be handled by the build system

### ISSUE THREAD

**Issue by norosa** [crate/crate-docs-theme#241]
https://github.com/crate/crate-docs-theme/commit/02bcb186bce9a9e6f1de356a9f84dc0e7a582204 introduced CSS minification. however, it looks like @msbt minified the CSS by hand. the result is that if you edit the source CSS files, your changes will not have any effect. the theme only reads the minified CSS and ignores the source CSS (which is working as intended)

we need a way of developing the CSS that doesn't require you to minify the CSS by hand every time you make a change. people who know you have to do this are likely to forget occasionally. and people who don't know this are likely to be confused about why their changes are not showing up

I am not sure what CSS minification tool @msbt used. we need to identify what tool to use before we can implement a build rule for doing this

I am guessing that the command to minify the CSS ought to be added after: https://github.com/crate/crate-docs-theme/blob/59905a67e9b064641c1ee5058b10b5f8fab8a846/Makefile#L60

and before: https://github.com/crate/crate-docs-theme/blob/59905a67e9b064641c1ee5058b10b5f8fab8a846/Makefile#L61

no other changes ought to be necessary. the `Makefile` in `docs` uses the `crate-docs-theme` package that is built in the parent directory, so any changes made to that package will show up when you view the test docs (as long as a `make reset` is run every time changes are made, to clear the local Python package cache).

---

this issue came up while working on https://github.com/crate/tech-writing-domain/issues/382

as an interim workaround, I plan to fix the CSS issue I am working on and generate a new minified CSS by hand and check it into the repository to replace the existing one

**Comment by mechanomi** [comment]
@msbt can you provide some guidance re what tooling we should use for automating the minification? additionally, is there anything else like this we ought to roll into the build?

**Comment by msbt** [comment]
I'm using the npm packages **uglifyjs**

`"uglifyjs ../../crate-docs-theme/src/crate/theme/rtd/crate/static/js/modernizr.js ../../crate-docs-theme/src/crate/theme/rtd/crate/static/js/underscore.min.js ../../crate-docs-theme/src/crate/theme/rtd/crate/static/js/searchtools.js ../../crate-docs-theme/src/crate/theme/rtd/crate/static/js/webflow.js ../../crate-docs-theme/src/crate/theme/rtd/crate/static/js/sticky-sidebar.min.js -o ../../crate-docs-theme/src/crate/theme/rtd/crate/static/js/script.min.js -c -m",`

 for the javascript files and **postcss**

`"minify-docs": "postcss --use postcss-import --map false  --use cssnano  --output ../../crate-docs-theme/src/crate/theme/rtd/crate/static/css/style.min.css ../../crate-docs-theme/src/crate/theme/rtd/crate/static/css/style-min.css"`

for the minification, the updated package.json file is [here](https://github.com/crate/website-theme/blob/master/_build/package.json). 

If you want to try it manually, just grab the package.json (adjust the path to the theme files), do a `npm install` and then `npm run minify-docs` or `npm run uglify-docs`. Not sure how you would implement that in the build process though, but I imagine there are various ways to do it.

**Comment by msbt** [comment]
@mechanomi Also, I specifically left out `custom.css` and `custom.js` of the minification process, so any quick changes can be made easily without minifying the whole thing again.

**Comment by mechanomi** [comment]
@msbt I see. thanks!

please can you put that information (both comments) in the `DEVELOP.rst` file? I think that would be a good first step. then perhaps @amotl is up for working with you to integrate this into the build somehow? the file that needs modifying is the top-level `Makefile`, not `docs/Makefile`

please can you also take a look at my CSS changes on https://github.com/crate/crate-docs-theme/pull/242? should that change be in the `crateio-rtd.css` file? I'd rather make the change to the correct file and then minify things if necessary

please note: so far, I have been unable to test my change on that PR because I have not yet tried to minify anything

**Comment by msbt** [comment]
@mechanomi I'm not quite sure how those different css files came about and I mostly edit the custom.css myself. When I have a little time I might check out the `crateio.css` and `crateio-rtd.css` and do some cleaning, not sure why we need all those.

I've created a quick PR for the `DEVELOP.rst` which also introduces a quick fix for the rating system, let me know if this is alright: https://github.com/crate/crate-docs-theme/pull/243

**Comment by mechanomi** [comment]
that seems like a good interim solution. thanks!

I would eventually like the minification to be implemented into the build system though. is that something you want to do? or should we ask @amotl to take this over?

also, do you think we should close this issue and punt the build integration. or should we attempt to fix it now?

**Comment by msbt** [comment]
Since the build process relies on python, maybe @amotl could see if there's a solution that doesn't require nodejs to be part of the equation to keep it simpler. I've never done that, so it might be cool if he could check it out.

Not sure what you mean with the last part, if there's a rather quick solution for the minification process, lets do it, if not, lets figure out the best approach.

**Comment by amotl** [comment]
Hi,

I started working on this and hope to be able to submit a patch soon. I already introduced the new bundling system to @msbt and he likes it. It will be based on yarn and webpack, like many other contemporary web applications building on top of HTML, JavaScript and CSS.

With kind regards,
Andreas.
