### ISSUE TITLE
Rework syntax highlighting of code snippets

### ISSUE THREAD

**Issue by amotl** [crate/crate-docs-theme#257]
If we want to go totally crazy, we could rework the code-boxes / syntax highlighting 😬 
![image](https://user-images.githubusercontent.com/23557193/114839547-30aae380-9dd6-11eb-9c68-580275704ed8.png)
-- https://crate.io/docs/crate/tutorials/en/latest/install.html

_Originally posted by @proddata in https://github.com/crate/crate-docs-theme/issues/248#issuecomment-820234534_

**Comment by proddata** [comment]
I hope it is clear, that I only quickly changed the `font` and `background` color, and this wouldn't be my "favourite" colours after all :D

I think in general it would improve readability if the background of code-blocks is not grey, as the code parts are separated from the text parts.

![image](https://user-images.githubusercontent.com/23557193/115350428-63c5ec00-a1b5-11eb-8c17-6fe7120a4867.png)

**Comment by proddata** [comment]
For reference:

**Influx**
![image](https://user-images.githubusercontent.com/23557193/115351014-15651d00-a1b6-11eb-9c18-268198201ca0.png)

**MongoDB**
![image](https://user-images.githubusercontent.com/23557193/115351080-257cfc80-a1b6-11eb-9f4f-7a6739c1d163.png)

**Timescale**
![image](https://user-images.githubusercontent.com/23557193/115350932-fbc3d580-a1b5-11eb-8458-73c49362b20d.png)

**Comment by amotl** [comment]
@belringer commented at https://github.com/crate/crate-docs-theme/pull/248#issuecomment-822394865:
> I suggest color `#000000` and additionally `font-weight: bold;`

**Comment by proddata** [comment]
> @belringer responded at [#248 (comment)](https://github.com/crate/crate-docs-theme/pull/248#issuecomment-822394865):
> 
> > I suggest color `#000000` and additionally `font-weight: bold;`

I think this was for `h4`, but not for code-snippets 😬

**Comment by amotl** [comment]
Hi @proddata,

on my machine, the cited documentation section looks like this:

![image](https://user-images.githubusercontent.com/453543/119653053-2b09da00-be27-11eb-98a2-2a407f8d6fea.png)

I believe it is not that bad. What exactly would you suggest here?

With kind regards,
Andreas.

/cc @msbt

**Comment by amotl** [comment]
> P.S.: The syntax highlighting is implemented by the fine [Pygments](https://pypi.org/project/Pygments/) package.

Apparently, Pygments implements different kinds of styles already, see https://pygments.org/docs/styles/. Let me know if you would like to see a different one.

**Comment by amotl** [comment]
[1] lists some pointers to example style galleries. [2] hosts a demo page from the Pygments project itself, while [3,4,5] seem to be galleries implemented by others. [5] seems to be the most exhaustive and convenient one.

[1] https://superuser.com/questions/374509/where-can-i-find-a-gallery-of-pygments-css-files
[2] https://pygments.org/demo/
[3] https://help.farbox.com/pygments.html
[4] https://blog.yjl.im/2015/08/pygments-styles-gallery.html
[5] https://stylishthemes.github.io/Syntax-Themes/pygments/

**Comment by amotl** [comment]
What about Darcula?

### SQL
![image](https://user-images.githubusercontent.com/453543/119654879-32ca7e00-be29-11eb-987f-6c4573c63dfe.png)

### Python
![image](https://user-images.githubusercontent.com/453543/119654918-3e1da980-be29-11eb-9378-49848ef11c66.png)

**Comment by proddata** [comment]
Material might fit with the color scheme 😬 
![image](https://user-images.githubusercontent.com/23557193/119655129-8341db80-be29-11eb-91ea-7938a5749c15.png)

**Comment by amotl** [comment]
Hi again,

thank you for your feedback. I've implemented this with #273.

With kind regards,
Andreas.
