### ISSUE TITLE
Fix and improve OpenGraph metadata

### ISSUE THREAD

**Issue by amotl** [crate/crate-docs-theme#278]
Hi there,

#269 adds OpenGraph metadata to each documentation page. When looking at the respective information on https://crate.io/docs/crate/tutorials/en/latest/, this produces:
```html
<meta property="og:title" content="CrateDB Tutorials" />
<meta property="og:type" content="website" />
<meta property="og:url" content="https://crate.io/index.html" />
<meta property="og:site_name" content="CrateDB documentation" />
<meta property="og:description" content="CrateDB is a distributed SQL database that makes it simple to store and analyze massive amounts of machine data in real-time. Table of contents Installation, First use, Create user, Create sharded table, Generate time series data, Normalize time series data intervals." />
<meta property="og:image" content="https://user-images.githubusercontent.com/453543/119536319-3c9ca480-bd89-11eb-908d-3da78e55f17b.png" />
```

From my perspective, `<meta property="og:url" content="https://crate.io/index.html" />` is wrong. Following this link will yield a 404 page.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Maybe this is related to #220?

**Comment by msbt** [comment]
@amotl it's only using the urls relative to the repo and omitting everything before, so when visiting

https://crate.io/docs/crate/howtos/en/latest/performance/index.html

the og url is https://crate.io/performance/index.html - which is obviously a 404, it only uses the portion `performance/index.html` of the url and cuts out this part `/docs/crate/howtos/en/latest/`

**Comment by amotl** [comment]
Hi Matthias,

do you believe #280 might fix it?

With kind regards,
Andreas.
