### ISSUE TITLE
The version drop-down menu no longer works

### ISSUE THREAD

**Issue by norosa** [crate/crate-docs-theme#281]
Steps to reproduce:

1. visit any page, e.g., https://crate.io/docs/crate/reference/en/4.5/index.html
2. click the version drop-down menu (at time of writing, the menu selection defaults to "v:4.5")

What happens:

- nothing

What I expect to happen:

- the drop-down menu shows me a list of available versions that I can select from

Tested using:

  - Chrome on macOS (with hard refresh and incognito mode)
  - Safar on macOS (ditto)

More:

I see lots of errors (or things that look like issues) in the dev console. I expect this relates to https://github.com/crate/crate-docs-theme/issues/277. however, clicking the drop-down does not produce any new errors in addition to the messages that already appear

**Comment by norosa** [comment]
cc @msbt @amotl

**Comment by msbt** [comment]
@norosa this could be related to the position of jquery in the order of loading things, I'll talk @amotl to see what we can do about it

**Comment by amotl** [comment]
Is it possible to have lost this feature when dropping the bootstrap.js file?

**Comment by msbt** [comment]
close, it seems to be related to the webflow.js we were using, seems to be a bit over the top, having a 140k library for a hover effect ;) when I have time I could rebuild the thing, but can we readd it for now so it works again?

**Comment by amotl** [comment]
Here we go: #282.

**Comment by amotl** [comment]
Thanks for your suggestion at https://github.com/crate/crate-docs-theme/pull/282#issuecomment-849726064, #283 might get things straight?

**Comment by amotl** [comment]
Hi again,

the problem has been fixed. I verified it on those pages:

- https://crate.io/docs/crate/reference/
- https://crate.io/docs/crate/tutorials/
- https://crate.io/docs/crate/howtos/

With kind regards,
Andreas.

**Comment by norosa** [comment]
thanks so much folks!!
