### ISSUE TITLE
Use theme to set all requirements for Crate Sphinx projects

### ISSUE THREAD

**Issue by norosa** [crate/crate-docs-theme#294]
I am creating this issue to address the underlying cause of https://github.com/crate/crate-jdbc/issues/342.

### How dependency resolution is done at build time

- When RTD tries to build a Sphinx project, it reads the requirements from `docs/requirements.txt`.

  See below for examples.

- Every `docs/requirements.txt` file specifies the `crate-docs-theme`.

  Some (most?) `docs/requirements.txt` files also specify additional dependencies (for example, to pin a specific version of `sphinx`)

- The `crate-docs-theme` package [setup.py](https://github.com/crate/crate-docs-theme/blob/main/setup.py) file includes an [install_requires](https://github.com/crate/crate-docs-theme/blob/5302edf75046895d0cb8c49439ed2e00f8eaf725/setup.py#L59) list that also specifies dependencies (for example, to pin a specific version of `sphinx`).

### Degrees of freedom

- The specifications in `docs/requirements.txt`  are fixed to the HEAD commit of the branch you are trying to build. There is no way to alter this configuration without updating the HEAD commit.

  For `main` or `master`, this typically isn't an issue.
  
  For release branches, this will involve a cherry-pick backport. Sometimes, backporting a simple docs configuration change to an older release branch of a software project causes unrelated test failures for the main project code. This can happen when the new test environment that was created to test the PR pulled in newer dependencies that were used before. These newer dependencies may introduce breaking changes, regressions, and so on. This typically requires one of the core project maintainers to spend some time fixing a bunch of unrelated project code tests.

- The specifications listed in `setup.py` vary across versions of the `crate-docs-theme` package.

  When Pip is trying to satisfy the two sets of requirements, the only option _at build time_ is to cycle through older versions of the `crate-docs-theme` package until one is found that does not conflict with `docs/requirements.txt`.

### Conclusion

- Any time `docs/requirements.txt` lists a package already listed as a dependency of the `crate-docs-theme` package (via `setup.py`), you open yourself up to "surprise" builds where RTD selects an old version of the theme. This will result in one or more of the live documentation projects using an out-of-date design (breaking seamless integration with the rest of the website).

  See https://github.com/crate/crate-jdbc/issues/342 for an example of this.

### [crate](https://github.com/crate/crate/blob/master/docs/requirements.txt)

```
# packages for RTD to pick up (not used for local dev)
crate-docs-theme>=0.12.0
sphinx-csv-filter
Pygments>=2.7.4,<3
```

### [crate-tutorials](https://github.com/crate/crate-tutorials/blob/master/docs/requirements.txt)

```
sphinx==3.5.4
docutils==0.16
crate-docs-theme
```

### [crate-howtos](https://github.com/crate/crate-howtos/blob/master/docs/requirements.txt)

```
crate-docs-theme
```

### [crate-clients-tools](https://github.com/crate/crate-clients-tools/blob/master/docs/requirements.txt)

```
crate-docs-theme
```

### [crash](https://github.com/crate/crash/blob/master/docs/requirements.txt)

```
crate-docs-theme
```

### [admin-ui](https://github.com/crate/crate-admin/blob/master/docs/requirements.txt)

```
crate-docs-theme
```

### [crate-python](https://github.com/crate/crate-python/blob/master/docs/requirements.txt)

```
crate-docs-theme
```

### [crate-jdbc](https://github.com/crate/crate-jdbc/blob/master/docs/requirements.txt)

```
# don't pin crate version numbers so the latest will always be pulled when you
# set up your environment from scratch

crate-docs-theme>=0.7

# packages for local dev

sphinx-autobuild==0.6.0

# the next section should mirror the RTD environment

alabaster>=0.7,<0.8,!=0.7.5
setuptools<41
sphinx==1.8.5
```

### [crate-dbal](https://github.com/crate/crate-dbal/blob/main/docs/requirements.txt)

```
crate-docs-theme
```

### [crate-pdo](https://github.com/crate/crate-pdo/blob/main/docs/requirements.txt)

```
crate-docs-theme
```

### [crate-npgsql](https://github.com/crate/crate-npgsql/blob/master/docs/requirements.txt)

```
crate-docs-theme
```

### [cloud-tutorials](https://github.com/crate/cloud-tutorials/blob/master/docs/requirements.txt)

```
crate-docs-theme
```

### [cloud-howtos](https://github.com/crate/cloud-howtos/blob/master/docs/requirements.txt)

```
crate-docs-theme
```

### [cloud-reference](https://github.com/crate/cloud-reference/blob/master/docs/requirements.txt)

```
crate-docs-theme
```

### [croud](https://github.com/crate/croud/blob/master/docs/requirements.txt)

```
# Standard packages needed for the docs
###############################################################################

crate-docs-theme


# Project specific packages
###############################################################################

# Pip is run from the root directory, so this installs the `croud` package
.
sphinx-argparse==0.2.5
```

### [sql-99](https://github.com/crate/sql-99/blob/master/docs/requirements.txt)

```
crate-docs-theme
```

### [crate-docs](https://github.com/crate/crate-docs/blob/main/docs/requirements.txt)

```
sphinx==3.5.3
crate-docs-theme
```

### [crate-docs-theme](https://github.com/crate/crate-docs-theme/blob/main/docs/requirements.txt)

```
# Install the local crate-docs-theme package by specifying parent directory,
# because `pip` is run from there.
--editable=.
sphinx==3.5.4
docutils==0.16
```

## Proposed solution

Premise:

- The `crate-docs-theme` should specify all requirements in the [setup.py](https://github.com/crate/crate-docs-theme/blob/main/setup.py) file and the Sphinx project-specific `docs/requirements.txt` file should only list a single dependency: `crate-docs-theme` (not pinned to any version, so the latest is always used).

Some of the projects already do this (see above).

To complete this work, I propose that we:

- Update all `docs/requirements.txt` files so they only specify `crate-docs-theme` as a dependency
  - Backport this change to active release branches as necessary

Projects needing updates as above:

- [ ] [crate](https://github.com/crate/crate/blob/master/docs/requirements.txt)
- [ ] [crate-tutorials](https://github.com/crate/crate-tutorials/blob/master/docs/requirements.txt)
- [ ] [crate-jdbc](https://github.com/crate/crate-jdbc/blob/master/docs/requirements.txt)
- [ ] [croud](https://github.com/crate/croud/blob/master/docs/requirements.txt)
- [ ] [crate-docs](https://github.com/crate/crate-docs/blob/main/docs/requirements.txt)

The theme also needs updating:

- [ ] [crate-docs-theme](https://github.com/crate/crate-docs-theme/blob/main/docs/requirements.txt)

  However, the `crate-docs-theme` `docs/requirements.txt` file is an exception.

  The `--editable=.` essentially installs the `crate-docs-theme` package from the parent directory, so that you can test changes to theme by building the docs. This line should stay. The next two lines (`sphinx` and `docutils`) can probably be removed.

**Comment by norosa** [comment]
@amotl take a look and let me know what you think. I'm happy to create the PRs and do the work to fix this issue. but I also thought you might like to take a shot? (i.e., to share knowledge/experience)

**Comment by amotl** [comment]
> The crate-docs-theme should specify all requirements in the setup.py file and the Sphinx project-specific docs/requirements.txt file should only list a single dependency: crate-docs-theme (not pinned to any version, so the latest is always used).

I second this.

**Comment by amotl** [comment]
In this context, I would also like to reference https://github.com/crate/crate-docs/pull/52.

**Comment by amotl** [comment]
Would leaving project-specific dependencies like `sphinx-csv-filter` for `crate` or `sphinx-argparse` for `croud` do any harm to this plan?

**Comment by norosa** [comment]
1. sweet!! thanks so much
2. which dependencies? (i.e., what file or files are you referencing?)
3. yeah I think that's fine. should be no problem to leave those project-specific deps in there

**Comment by amotl** [comment]
> 2. which dependencies? (i.e., what file or files are you referencing?)

Yeah, I actually meant those referenced at 3., apart from `crate-docs-theme`, at:

[2a] https://github.com/crate/crate/blob/master/docs/requirements.txt
[2b] https://github.com/crate/croud/blob/master/docs/requirements.txt

All set!

**Comment by amotl** [comment]
@norosa: Do you believe we can close this ticket or is there some more work to do which I might be missing?

**Comment by norosa** [comment]
@amotl thanks for all the work!
