### ISSUE TITLE
There are different doc-template versions in use when accessing specific version vs. /latest/

### ISSUE THREAD

**Issue by msbt** [crate/crate-docs-theme#345]
Example:
https://crate.io/docs/python/en/0.22/
uses the correct template, the outdated note links to [v0.23](https://crate.io/docs/python/en/0.23/)

https://crate.io/docs/python/en/0.23/
uses an outdated template, supposed to be the same as [/latest/](https://crate.io/docs/python/en/latest/)

https://crate.io/docs/python/en/latest/
uses the correct template again

Same issue occurs on those docs pages/versions:
https://crate.io/docs/pdo/en/1.0/
https://crate.io/docs/jdbc/en/2.6/
https://crate.io/docs/jdbc/en/2.5/

**Comment by amotl** [comment]
Can you try to rebuild the corresponding documentation artefacts per https://readthedocs.org/dashboard/ and check if that improves the situation?

**Comment by amotl** [comment]
Hi again,

we recently improved things in this area. Can you re-evaluate your report and close this ticket when applicable?

With kind regards,
Andreas.

**Comment by msbt** [comment]
Most of the repos look good, but
https://crate.io/docs/jdbc/en/2.6/ still has the old favicon and
https://crate.io/docs/jdbc/en/2.5/ the old favicon and logo, but this could also be cache-related, I'll do some purging and get back to you

**Comment by msbt** [comment]
all looking good now, thanks!
