### ISSUE TITLE
Synchronize forwarding of the `/latest/` URLs

### ISSUE THREAD

**Issue by msbt** [crate/crate-docs-theme#346]
Only the "reference" and "dbal" projects forward the `/latest/`-version URLs to a specific documentation version, on the others both can be accessed separately.

Example:
https://crate.io/docs/dbal/en/latest/ forwards to https://crate.io/docs/dbal/en/2.3/

Not really an issue, but would be nice to have all the doc-repos work the same way, so either 
- forward all `/latest/` links to the actual version (like https://crate.io/docs/dbal/en/latest/)
- make both accessable (like https://crate.io/docs/jdbc/en/latest/ - but making sure that it's actually the same content)

**Comment by amotl** [comment]
Thank you for reporting this. So, do you think we should adjust both "reference" and "dbal" projects to behave like the others?

**Comment by msbt** [comment]
I'm not a 100% sure. Having separate pages with both, the release number and /latest might cause duplicate content warning. Maybe @michaelkremmel could chime in and give a suggestion.

**Comment by msbt** [comment]
@amotl I had a talk with @michaelkremmel and we came to the conclusion that automated redirects from /latest/ to the corresponding versions are not really necessary. They could be accessed separately (like it's currently the case with the [JDBC](https://crate.io/docs/jdbc/en/latest/) repo. The canonical URL already points to the /latest version anyways, so we shouldn't get penalties for duplicate content.

What's the take from others? Is there a reason why we're redirecting from latest to the version on the Reference and DBAL repos but not the others? cc @mfussenegger @seut @matkuliak

**Comment by amotl** [comment]
Hi again. Has this been fixed by this other patch?

- https://github.com/crate/infrastructure/pull/3152

Do you think we can close the issue, or are there some leftovers to consider?

**Comment by msbt** [comment]
@amotl yes, I think we removed all redirects to versioned docs, thanks
