### ISSUE TITLE
`/latest/` doesn't link to the latest version

### ISSUE THREAD

**Issue by msbt** [crate/crate-docs-theme#347]
Example:
https://crate.io/docs/crate/crash/en/latest/ forwards to https://crate.io/docs/crate/crash/en/0.27/ which is not the latest version, [0.28](https://crate.io/docs/crate/crash/en/0.28/) is. So the note is right, but the redirect from /latest/ is pointing to the wrong version.

**Comment by amotl** [comment]
On this matter, @hammerhead just submitted https://github.com/crate/infrastructure/pull/2891.

**Comment by amotl** [comment]
I've just applied the change. I think the problem is fixed. Can you confirm?

**Comment by msbt** [comment]
nice, looking good! thanks @amotl and @hammerhead 🙌
