### ISSUE TITLE
Problem with sphinx-copybutton

### ISSUE THREAD

**Issue by msbt** [crate/crate-docs-theme#354]
### Problem
When copying snippets including prompts, and something is wrong on the indentation side, copy doesn't work properly.

### Examples
- https://crate.io/docs/crate/howtos/en/latest/getting-started/generate-time-series/cli.html#set-up-cratedb

**Comment by amotl** [comment]
Hi Matthias,

thanks for the report. Our focus was that doctest-style multiline _SQL statements_ with proper continuation symbols work flawlessly. For example, https://crate.io/docs/crate/reference/en/5.0/general/ddl/partitioned-tables.html#information-schema.

However, something obviously goes wrong on certain multiline _console snippets_.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Unable to rebuild `crate-howtos` to confirm this will be resolved now.

-- https://github.com/crate/crate-howtos/pull/310#issuecomment-1192448703

**Comment by amotl** [comment]
All the terminal-based code blocks on https://crate.io/docs/crate/howtos/en/latest/getting-started/generate-time-series/cli.html should work now, copy/paste-wise.

Another flaw with the SQL DDL block should be mitigated by https://github.com/crate/crate-howtos/pull/311.

**Comment by msbt** [comment]
thanks @amotl, I'll close this for now since I don't have any other errors like that :)
