### ISSUE TITLE
Improving feedback and version choosers

### ISSUE THREAD

**Issue by kojinkai** [crate/crate-docs-theme#413]
### Documentation feedback

 
- Page title: CrateDB Cloud
- Page URL: https://crate.io/docs/cloud/en/latest/index.html
- Source: https://github.com/crate/cloud-docs/blob/main/docs/index.md

---

Both the settings and version flyout menus can be opened at the same time. Perhaps opening one menu should close the other open menu.

<img width="355" alt="error" src="https://github.com/crate/cloud-docs/assets/855218/2ed6b671-0fa8-4bf2-9111-59916264ba75">

**Comment by amotl** [comment]
Dear Lewis,

thanks for reporting. I am not sure if we can synchronize both elements easily. Would it be a reasonable option to increase the `z-index` value of the left-hand element (Feedback chooser) at least?

With kind regards,
Andreas.

**Comment by amotl** [comment]
16ac241a26 attempts to improve the situation. I admit it is still flawed, but at least a bit better than before?

![image](https://github.com/crate/crate-docs-theme/assets/453543/787abe41-8430-4ab5-a353-d1f848c4eea0)

**Comment by amotl** [comment]
There are two more improvements related to this topic. Thanks, @msbt.

- GH-415
- GH-417

**Comment by amotl** [comment]
We just discovered yet another issue. When expanding the chooser, and then scrolling the page, you will immediately discover the flaw. Do you have any suggestions, @msbt?

![image](https://github.com/crate/crate-docs-theme/assets/453543/935ee6f3-6b10-45ff-985b-47d091d75b8c)

**Comment by msbt** [comment]
@amotl that's why I suggested `position: absolute;` at some point 😉

something along the lines of 

```
.feedback-compact-content div.sd-summary-content,
.version-chooser-content div.sd-summary-content {
  position: absolute;
  z-index: 175;
  background: #fff;
  border: 1px solid #ccc;
  width: max-content;
}
```

Can you give that a whirl and see if it fixes things and not make them worse?

**Comment by amotl** [comment]
Thanks. It would be your turn now ;].

**Comment by msbt** [comment]
@amotl https://github.com/crate/crate-docs-theme/pull/425

**Comment by amotl** [comment]
I think it is safe to close this issue now. Thank you all for your feedback and contributions to improve the situation. Please let us know if you can think of any further improvements, or if you discover any glitches.

**Comment by amotl** [comment]
GitBook provides a nice widget for this purpose.

![image](https://github.com/crate/crate-docs-theme/assets/453543/52c2daf4-d0dd-4e78-8484-5829b49ec6ae)

-- https://docs.activeloop.ai/quickstart
-- https://docs.activeloop.ai/tutorials/vector-store/deep-lake-vector-store-in-langchain

**Comment by msbt** [comment]
@amotl nice! (although, I do like to access links manually, not via JS events, so I can open them in a new window if I want or paste them somewhere else 😉) What's the plan, should we rebuild the thing for Sphinx? 

Do you also have an idea for a more extensive feedback option? I got asked to readd something along the lines of "Was this content helpful?" or a star-rating like we used to have. Gitbook has that at the bottom as well.

**Comment by seut** [comment]
Looks like the original scope is done.
