### ISSUE TITLE
Documentation: Set up comprehensive G4A view

### ISSUE THREAD

**Issue by matkuliak** [crate/crate-docs-theme#494]
It's possible to find out everything you need of course, but there isn't a nice quick overview of important metrics.

**Comment by msbt** [comment]
@matkuliak not sure if the public repo is the right place for that ;)

**Comment by matkuliak** [comment]
Edited, just to have a ticket on GitHub.

**Comment by matkuliak** [comment]
Not perfect, but solved w/ @geragray
