### ISSUE TITLE
Version toggler and feedback dropdown look odd

### ISSUE THREAD

**Issue by amotl** [crate/crate-docs-theme#497]
@msbt reported a visual regression.

> Quick FYI: I realized earlier that the version toggler and feedback dropdown on the docs look odd and while debugging, figured out that there was an update of one of the packages that we have in use (https://github.com/executablebooks/sphinx-design/tags). This update/regression caused the layout to fail.
>
> ![image](https://github.com/crate/crate-docs-theme/assets/453543/c15b0910-7803-4885-8720-da55a982deb4)

**Comment by amotl** [comment]
@msbt figured the regression has been caused by [sphinx-design-0.6.0](https://github.com/executablebooks/sphinx-design/releases/tag/v0.6.0), released just five days ago.

**Comment by msbt** [comment]
thanks @amotl, this seems to be the corresponding patch, where they change from chevron up/down to left/down: https://github.com/executablebooks/sphinx-design/pull/192

**Comment by amotl** [comment]
Thanks. I can't spot the regression you outlined at https://cratedb.com/docs/crate/reference/ ff.

**Comment by amotl** [comment]
I totally accept and appreciate that you spotted an error, but for me, it is not visible in any way.

**Comment by amotl** [comment]
I am asking because a downgrade to a previous version of sphinx-design would be totally a no-brainer, like outlined at https://github.com/crate/crate-docs-theme/issues/497#issuecomment-2134700205.

However, because I can't spot any regression anywhere, I am doubting that it makes sense, because it will not make too much of a difference from my perspective.

**Comment by matkuliak** [comment]
One thing to mention for anyone working on this, @msbt was able to patch this by injecting CSS with HubSpot - via fastly edge side includes, from what I understand.

**Comment by amotl** [comment]
Ah I see. Now it totally makes sense that I can't spot any mistake, if it has already been fixed using a workaround. Thanks for clarifying.

**Comment by amotl** [comment]
Now, everything makes sense. Thanks for clarifying.

NB: Please don't use URLs verbatim in public which can feed crawlers wrongly.

**Comment by amotl** [comment]
Because sphinx-design 0.6 also trips software tests on sphinx-design-elements, and because I currently don't have the capacity to review and fix them, I am already downgrading on behalf of sphinx-design-elements.

- https://github.com/tech-writing/sphinx-design-elements/pull/84

**Comment by amotl** [comment]
[sphinx-design-elements](https://pypi.org/project/sphinx-design-elements/) v0.3.2 downgrades to [sphinx-design ](https://pypi.org/project/sphinx-design/) v0.5, so the next downstream builds of crate-docs-theme should pick up corresponding package versions, effectively resolving this issue.

Please verify, report back, and/or close this issue, at your disposal. Thanks.

**Comment by amotl** [comment]
I've rebuilt all docs, and purged the Fastly cache on all documentation projects afterwards.

**Comment by amotl** [comment]
> @amotl you can see the regression on any non-proxied url, e.g. `https://crash.readthedocs.io/en/latest/`. The padding changed and also the chevrons.

It looks like it is fixed through the downgrading outlined above.

**Comment by amotl** [comment]
I just found that in the [changelog for sphinx-design 0.6](https://sphinx-design.readthedocs.io/en/furo-theme/changelog.html#improve-dropdown-title-bar):

> The "default" behaviour of the right chevron is to go from right-facing (closed) to down-facing (open), instead of down-facing (closed) to up-facing (open). There is also a rotate transition on opening/closing. The old default behaviour can be retained by using the new `:chevron: down-up` directive option.

**Comment by amotl** [comment]
We concluded the resolution of this flaw by adding relevant fixes and releasing [crate-docs-theme 0.33.0](https://github.com/crate/crate-docs-theme/releases/tag/0.33.0). @msbt: Thanks for your support!

**Comment by msbt** [comment]
@amotl apparently the docs are still being built with the old version (`Downloading crate_docs_theme-0.32.4-py3-none-any.whl (2.1 MB)`) - any idea what's going on there?

**Comment by amotl** [comment]
[Build #24863053 on "crash"](https://readthedocs.org/projects/crash/builds/24863053/) says it uses `crate-docs-theme-0.33.0` already.

**Comment by msbt** [comment]
@amotl that was back when the 0.33.0 wasn't on pyi
