### ISSUE TITLE
update docs and build to account for removal of LESS

### ISSUE THREAD

**Issue by mechanomi** [crate/crate-docs-theme#50]
we stopped compiling LESS to CSS in 0.5.0 apparently, but it looks like the `README.rst` and `Gruntfile.js` (and perhaps some other things) were not updated. these should be updated. perhaps we want to remove Grunt entirely?

**Comment by nslater** [comment]
@chaudum how much of what's listed under (Development](https://github.com/crate/crate-docs-theme#development) in `README.rst` is actually needed any more? can we rip it all out or is the buildout stuff needed?
