### ISSUE TITLE
Page Tool button style is slightly off

### ISSUE THREAD

**Issue by amotl** [crate/crate-docs-theme#505]
## Problem
After successful fixes to the design/layout of the page tool elements (version toggler & docs feedback), like GH-497, and other measures like GH-501, we thought everything would be in order. However, it is not. The icons within the button elements are slightly off, and also, it appears like the height of the buttons is less than intended.

![image](https://github.com/crate/crate-docs-theme/assets/453543/a72a9744-a45d-4672-a547-1601846e8425)

/cc @msbt

**Comment by msbt** [comment]
@amotl I still can't reproduce this, however, I added a one-liner fix like last time, can you check if it's better now?

**Comment by amotl** [comment]
The weird offset is gone (thanks!), but the buttons are still smaller than originally. However, I also like the slim appearance.
Where did you apply the fix?

**Comment by msbt** [comment]
@amotl Through the edge side include of the notification header, piggybacked on that to inject the css ;)

**Comment by amotl** [comment]
Thanks. Can you try to submit a corresponding patch that manifests the fix without the workaround?

**Comment by amotl** [comment]
I guess this has been fixed and can be closed safely. Thanks!
