### ISSUE TITLE
Version chooser missing after upgrading to 0.34.0

### ISSUE THREAD

**Issue by amotl** [crate/crate-docs-theme#517]
## Problem
After upgrading to the modernized theme, version choosers are missing at relevant spots.

- https://cratedb.com/docs/jdbc/
- https://cratedb.com/docs/reference/

## Thoughts
That's weird, @msbt's [most recent preview](https://crate-docs-theme--510.org.readthedocs.build/en/510/) still displays it.
![image](https://github.com/user-attachments/assets/7d3fc208-35db-4e2b-9cee-5a87e21ee4f4)

On the theme itself, the version chooser also is present, see https://crate-docs-theme.readthedocs.io/.

**Comment by amotl** [comment]
@msbt shared that it is only rendered conditionally.

```
{%- if display_version %}
{% include "components/version_chooser.html" %}
{%- endif %}
```
-- https://github.com/crate/crate-docs-theme/blob/main/src/crate/theme/rtd/crate/sections/sidebar-secondary.html#L13-L15

That's sweet, but why doesn't it work any longer like before?

**Comment by msbt** [comment]
@amotl I just compared and before we were using

```
{%- if versions %}
{% include "version_chooser.html" %}
{%- endif %}
```

Not sure why it became `display_version`, but seems like an easy fix - will take care of it tomorrow.

**Comment by amotl** [comment]
I can remember we introduced `display_version` the other day, in order to be more explicit than implicit.

It has 13 hits across the org, so it can't be that wrong, at least it hasn't been in the past. See https://github.com/search?q=org%3Acrate%20display_version&type=code.

**Comment by msbt** [comment]
@amotl this is the corresponding commit: https://github.com/crate/crate-docs-theme/commit/638599314a5f8d0788759895ed3581a976c15254

I'm guessing we did that to enable the verson chooser in the demo theme, right? Which one do you suggest now to bring it back, `current_version` as it was in that commit or just `versions` as above?

**Comment by amotl** [comment]
Yeah, I think we did it because of this, at least that was the beginning of the story. If we should revert that, I don't know. What do you recommend?

Maybe honor both flags? Wouldn't make too much sense, hm?

**Comment by msbt** [comment]
@amotl at least when rendering localhost it didn't change anything, same dropdown menus visible.

**Comment by amotl** [comment]
Maybe the announcement of this variable in some blueprint/master configuration file has been dropped?

**Comment by amotl** [comment]
`html_theme_options` are used here:

https://github.com/crate/crate-docs-theme/blob/134f2a863633f15d105e0e9bff7635e7f2068b04/src/crate/theme/rtd/conf/__init__.py#L67-L81

Defined, they are over there:
https://github.com/crate/crate-docs-theme/blob/134f2a863633f15d105e0e9bff7635e7f2068b04/src/crate/theme/rtd/crate/theme.conf

Maybe it will be enough to also define `display_version` here? I may be totally wrong on my assessment, just asking/suggesting without having done any research at all on this topic, yet.

**Comment by amotl** [comment]
> Which one do you suggest now to bring it back, `current_version` as it was in that commit or just `versions` as above?

I still think using `display_version` is currently the designated way of enabling the version chooser explicitly per project. If you can convince me to leave this behind, let's please have a session about it.

Otherwise, I think we may want to find out why it stopped working?

**Comment by msbt** [comment]
> It has 13 hits across the org, so it can't be that wrong, at least it hasn't been in the past. See https://github.com/search?q=org%3Acrate%20display_version&type=code.

@amotl ah yes, good call, but I guess we forgot/missed to add that `"display_version": True,` snippet to the repos which actually need to have versioned docs, like the reference?

**Comment by amotl** [comment]
That would be silly, but it's possible. Thanks!

**Comment by msbt** [comment]
@amotl So should we first try to update the reference repo to see if the version chooser appears then before changing the theme?

**Comment by amotl** [comment]
Yeah, I think this would be good. Thanks!
