### ISSUE TITLE
document how to test the theme

### ISSUE THREAD

**Issue by mechanomi** [crate/crate-docs-theme#56]
the recommended way to make changes to the theme and test them is to copy the `docs` folder from `crate/blackbox` into the `crate-docs-theme` root directory. I don't think symlinks work. and atm some files need editing. either way this should be documented

**Comment by MoaazGaballah** [comment]
Hello, 
I have a nodejs project which i want to make it's documentation using crate-docs-theme.
How to install that theme ?
I tried to use pip install crate-docs-theme command that's referred in README file here https://github.com/crate/crate-docs-theme
but nothing installed ! i also searched for a installation guide on this link 
https://sphinx-themes.org/html/crate-docs-theme/crate/index.html
 but also nothing 

any kind of help will be appreciated
